version: '3.8'

services:
  chatapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Development-specific logging
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - Logging__LogLevel__Microsoft.AspNetCore.SignalR=Debug
      - Logging__LogLevel__Microsoft.AspNetCore.Http.Connections=Debug
    volumes:
      # Mount source code for development (optional - for hot reload)
      # - .:/app/src:ro
      # Mount logs directory
      - ./logs:/app/logs
    ports:
      - "5000:8080"   # HTTP only
